from copy import deepcopy


RAW_COLUMNS = [
    "collected_time",
    "publish_time",
    "source_type",
    "source_name",
    "category_group",
    "title",
    "link",
    "summary",
    "keyword",
    "duplicate_flag",
    "normalized_title",
    "policy_score",
    "frame_category",
    "importance_score",
    "language",
    "notes",
    "body_text",
]

PROCESSED_COLUMNS = ["rank", *RAW_COLUMNS]

BRIEFING_COLUMNS = [
    "generated_time",
    "topic_name",
    "section_name",
    "content",
    "supporting_articles",
    "notes",
]

SOURCE_COLUMNS = [
    "enabled",
    "source_name",
    "source_type",
    "category_group",
    "feed_url",
    "keyword",
    "notes",
]

KEYWORD_COLUMNS = [
    "enabled",
    "bucket",
    "keyword",
    "weight",
    "notes",
]

RUNTIME_COLUMNS = [
    "key",
    "value",
    "notes",
]

DEFAULT_CONFIG = {
    "timezone": "Asia/Seoul",
    "topic": {
        "name": "보도자료 기반 미디어 모니터링",
        "announcementDate": "2026-01-01",
        "announcementDateTime": "2026-01-01T10:00:00+09:00",
    },
    "analysis": {
        "referenceTime": "",
    },
    "collection": {
        "maxItemsPerFeed": 100,
        "maxItemsPerGoogleNewsFeed": 50,
        "reportLookbackHours": 96,
        "maxProcessedRows": 50,
        "maxBriefingArticles": 12,
        "maxThemes": 3,
        "rawMinimumKeywordHits": 1,
        "rawCoreKeywords": [],
        "maxBodyFetchCandidates": 12,
        "bodyFetchMinimumPolicyScore": 4,
        "fetchBodyFromGoogleNews": False,
        "bodyTextMaxLength": 4000,
    },
    "dedup": {
        "fuzzyThreshold": 0.84,
    },
    "scoring": {
        "titleWeight": 3,
        "summaryWeight": 1,
        "bodyWeight": 0.75,
        "phraseBonus": 3,
        "highRelevanceThreshold": 8,
        "minimumKeywordHits": 2,
    },
    "ranking": {
        "majorOutletBoost": 4,
        "criticalFrameBoost": 2,
        "opinionBoost": 3,
        "repeatedNarrativeBonus": 1,
    },
    "genericThemeKeywords": [],
    "sourcePriority": {
        "연합뉴스": 4,
        "뉴스1": 3,
        "뉴시스": 3,
        "매일경제": 3,
        "한국경제": 3,
        "서울경제": 3,
        "이데일리": 2,
        "아시아경제": 2,
        "머니투데이": 2,
        "조선일보": 2,
        "중앙일보": 2,
        "동아일보": 2,
        "한겨레": 2,
        "경향신문": 2,
        "서울신문": 2,
        "세계일보": 2,
        "KBS": 3,
        "MBC": 3,
        "SBS": 3,
        "YTN": 3,
        "JTBC": 2,
        "노컷뉴스": 2,
        "헤럴드경제": 2,
        "파이낸셜뉴스": 2,
        "오마이뉴스": 1,
        "프레시안": 1,
        "데일리안": 1,
        "국토일보": 1,
        "건설경제": 1,
        "서울Pn": 1,
        "데일리머니": 1,
        "프레스뉴스": 1,
        "메가경제": 1,
    },
    "sources": [
        {
            "enabled": True,
            "source_name": "연합뉴스",
            "source_type": "rss",
            "category_group": "wire",
            "feed_url": "https://www.yna.co.kr/rss/news.xml",
            "keyword": "",
            "notes": "default source list",
        },
        {
            "enabled": False,
            "source_name": "뉴스1",
            "source_type": "rss",
            "category_group": "wire",
            "feed_url": "https://www.news1.kr/rss",
            "keyword": "",
            "notes": "default disabled on 2026-03-13: no working official RSS/sitemap feed confirmed; use Google News/manual URL fallback if needed",
        },
        {
            "enabled": False,
            "source_name": "뉴시스",
            "source_type": "rss",
            "category_group": "wire",
            "feed_url": "https://www.newsis.com/rss",
            "keyword": "",
            "notes": "default disabled on 2026-03-11: URL returned HTML, not RSS",
        },
        {
            "enabled": True,
            "source_name": "뉴시스-정치",
            "source_type": "rss",
            "category_group": "wire",
            "feed_url": "https://newsis.com/RSS/politics.xml",
            "keyword": "",
            "notes": "updated on 2026-03-11: verified working section RSS feed",
        },
        {
            "enabled": True,
            "source_name": "뉴시스-경제",
            "source_type": "rss",
            "category_group": "wire",
            "feed_url": "https://newsis.com/RSS/economy.xml",
            "keyword": "",
            "notes": "updated on 2026-03-11: verified working section RSS feed",
        },
        {
            "enabled": True,
            "source_name": "뉴시스-사회",
            "source_type": "rss",
            "category_group": "wire",
            "feed_url": "https://newsis.com/RSS/society.xml",
            "keyword": "",
            "notes": "updated on 2026-03-11: verified working section RSS feed",
        },
        {
            "enabled": True,
            "source_name": "조선일보",
            "source_type": "rss",
            "category_group": "national_daily",
            "feed_url": "https://www.chosun.com/arc/outboundfeeds/rss/?outputType=xml",
            "keyword": "",
            "notes": "updated on 2026-03-11: verified working direct RSS feed",
        },
        {
            "enabled": True,
            "source_name": "중앙일보",
            "source_type": "sitemap",
            "category_group": "national_daily",
            "feed_url": "https://www.joongang.co.kr/sitemap/latest-articles",
            "keyword": "",
            "notes": "updated on 2026-03-13: verified working latest-articles sitemap",
        },
        {
            "enabled": True,
            "source_name": "동아일보",
            "source_type": "rss",
            "category_group": "national_daily",
            "feed_url": "https://rss.donga.com/total.xml",
            "keyword": "",
            "notes": "default source list",
        },
        {
            "enabled": True,
            "source_name": "한겨레",
            "source_type": "rss",
            "category_group": "national_daily",
            "feed_url": "https://www.hani.co.kr/rss/",
            "keyword": "",
            "notes": "default source list",
        },
        {
            "enabled": True,
            "source_name": "경향신문",
            "source_type": "rss",
            "category_group": "national_daily",
            "feed_url": "https://www.khan.co.kr/rss/rssdata/total_news.xml",
            "keyword": "",
            "notes": "default source list",
        },
        {
            "enabled": True,
            "source_name": "서울신문",
            "source_type": "rss",
            "category_group": "national_daily",
            "feed_url": "https://www.seoul.co.kr/xml/rss/google_top.xml",
            "keyword": "",
            "notes": "updated on 2026-03-11: verified working RSS feed",
        },
        {
            "enabled": True,
            "source_name": "세계일보",
            "source_type": "rss",
            "category_group": "national_daily",
            "feed_url": "https://www.segye.com/Articles/RSSList/segye_recent.xml",
            "keyword": "",
            "notes": "default source list",
        },
        {
            "enabled": True,
            "source_name": "매일경제",
            "source_type": "rss",
            "category_group": "economic_daily",
            "feed_url": "https://www.mk.co.kr/rss/30000001/",
            "keyword": "",
            "notes": "default source list",
        },
        {
            "enabled": True,
            "source_name": "한국경제",
            "source_type": "rss",
            "category_group": "economic_daily",
            "feed_url": "https://www.hankyung.com/feed/all-news",
            "keyword": "",
            "notes": "default source list",
        },
        {
            "enabled": True,
            "source_name": "서울경제-부동산",
            "source_type": "rss",
            "category_group": "economic_daily",
            "feed_url": "https://www.sedaily.com/rss/realestate",
            "keyword": "",
            "notes": "updated on 2026-03-11: verified working section RSS feed",
        },
        {
            "enabled": True,
            "source_name": "서울경제-경제",
            "source_type": "rss",
            "category_group": "economic_daily",
            "feed_url": "https://www.sedaily.com/rss/economy",
            "keyword": "",
            "notes": "updated on 2026-03-11: verified working section RSS feed",
        },
        {
            "enabled": True,
            "source_name": "서울경제-정치",
            "source_type": "rss",
            "category_group": "economic_daily",
            "feed_url": "https://www.sedaily.com/rss/politics",
            "keyword": "",
            "notes": "updated on 2026-03-11: verified working section RSS feed",
        },
        {
            "enabled": True,
            "source_name": "이데일리",
            "source_type": "rss",
            "category_group": "economic_daily",
            "feed_url": "http://rss.edaily.co.kr/edaily_news.xml",
            "keyword": "",
            "notes": "updated on 2026-03-11: verified working RSS feed",
        },
        {
            "enabled": True,
            "source_name": "아시아경제",
            "source_type": "sitemap",
            "category_group": "economic_daily",
            "feed_url": "https://www.asiae.co.kr/news/sitemap-latest-article",
            "keyword": "",
            "notes": "updated on 2026-03-11: verified working news sitemap",
        },
        {
            "enabled": True,
            "source_name": "머니투데이",
            "source_type": "rss",
            "category_group": "economic_daily",
            "feed_url": "https://rss.mt.co.kr/mt_news.xml",
            "keyword": "",
            "notes": "default source list",
        },
        {
            "enabled": True,
            "source_name": "KBS",
            "source_type": "sitemap",
            "category_group": "broadcast",
            "feed_url": "https://news.kbs.co.kr/sitemap/recentNewsList.xml",
            "keyword": "",
            "notes": "updated on 2026-03-11: verified working news sitemap",
        },
        {
            "enabled": False,
            "source_name": "MBC",
            "source_type": "rss",
            "category_group": "broadcast",
            "feed_url": "https://imnews.imbc.com/rss/news.xml",
            "keyword": "",
            "notes": "default disabled on 2026-03-13: official RSS/sitemap URLs returned HTML pages, not usable feed XML",
        },
        {
            "enabled": True,
            "source_name": "SBS",
            "source_type": "rss",
            "category_group": "broadcast",
            "feed_url": "https://news.sbs.co.kr/news/SectionRssFeed.do?sectionId=01",
            "keyword": "",
            "notes": "default source list",
        },
        {
            "enabled": False,
            "source_name": "YTN",
            "source_type": "rss",
            "category_group": "broadcast",
            "feed_url": "https://www.ytn.co.kr/_rss/news.xml",
            "keyword": "",
            "notes": "default disabled on 2026-03-13: checked RSS/sitemap candidates returned HTML/404, not usable feed XML",
        },
        {
            "enabled": True,
            "source_name": "JTBC",
            "source_type": "rss",
            "category_group": "broadcast",
            "feed_url": "https://fs.jtbc.co.kr/RSS/newsflash.xml",
            "keyword": "",
            "notes": "default source list",
        },
        {
            "enabled": True,
            "source_name": "노컷뉴스",
            "source_type": "rss",
            "category_group": "online_media",
            "feed_url": "https://rss.nocutnews.co.kr/news/news.xml",
            "keyword": "",
            "notes": "updated on 2026-03-11: verified working RSS feed",
        },
        {
            "enabled": True,
            "source_name": "헤럴드경제",
            "source_type": "rss",
            "category_group": "online_media",
            "feed_url": "https://biz.heraldcorp.com/rss/google/newsAll",
            "keyword": "",
            "notes": "updated on 2026-03-11: verified working RSS feed",
        },
        {
            "enabled": True,
            "source_name": "파이낸셜뉴스",
            "source_type": "rss",
            "category_group": "online_media",
            "feed_url": "https://www.fnnews.com/rss/r20/fn_realnews_all.xml",
            "keyword": "",
            "notes": "updated on 2026-03-13: verified working official RSS XML feed",
        },
        {
            "enabled": True,
            "source_name": "오마이뉴스",
            "source_type": "rss",
            "category_group": "online_media",
            "feed_url": "https://rss.ohmynews.com/rss/ohmynews.xml",
            "keyword": "",
            "notes": "updated on 2026-03-11: verified working RSS feed",
        },
        {
            "enabled": True,
            "source_name": "프레시안",
            "source_type": "rss",
            "category_group": "online_media",
            "feed_url": "http://www.pressian.com/api/v3/site/rss/news",
            "keyword": "",
            "notes": "updated on 2026-03-11: verified working RSS feed",
        },
        {
            "enabled": True,
            "source_name": "데일리안",
            "source_type": "sitemap",
            "category_group": "online_media",
            "feed_url": "https://www.dailian.co.kr/sitemap/sitemap.xml",
            "keyword": "",
            "notes": "updated on 2026-03-13: verified working sitemap index",
        },
        {
            "enabled": True,
            "source_name": "국토일보",
            "source_type": "rss",
            "category_group": "policy_sector",
            "feed_url": "http://www.ikld.kr/rss/allArticle.xml",
            "keyword": "",
            "notes": "default source list",
        },
        {
            "enabled": True,
            "source_name": "서울Pn",
            "source_type": "sitemap",
            "category_group": "policy_sector",
            "feed_url": "https://go.seoul.co.kr/sitemap/sitemap_latestArticle",
            "keyword": "",
            "notes": "updated on 2026-03-12: verified working news sitemap",
        },
        {
            "enabled": True,
            "source_name": "데일리머니",
            "source_type": "rss",
            "category_group": "policy_sector",
            "feed_url": "https://www.thedailymoney.com/rss/allArticle.xml",
            "keyword": "",
            "notes": "updated on 2026-03-12: verified working RSS feed",
        },
        {
            "enabled": True,
            "source_name": "프레스뉴스",
            "source_type": "sitemap",
            "category_group": "policy_sector",
            "feed_url": "https://www.pressna.com/sitemap.xml",
            "keyword": "",
            "notes": "updated on 2026-03-12: verified working news sitemap",
        },
        {
            "enabled": True,
            "source_name": "메가경제",
            "source_type": "sitemap",
            "category_group": "policy_sector",
            "feed_url": "https://www.megaeconomy.co.kr/sitemap.xml",
            "max_items": 80,
            "keyword": "",
            "notes": "updated on 2026-03-13: verified working news sitemap; max_items raised to 80 because target article was at position 38",
        },
        {
            "enabled": True,
            "source_name": "건설경제",
            "source_type": "rss",
            "category_group": "policy_sector",
            "feed_url": "https://www.dnews.co.kr/rss/news_main.xml",
            "keyword": "",
            "notes": "updated on 2026-03-13: cnews robots now points to dnews RSS/sitemap endpoints",
        },
    ],
    "keywordRules": [
        {"enabled": True, "bucket": "frame_policy", "keyword": "발표", "weight": 1, "notes": ""},
        {"enabled": True, "bucket": "frame_policy", "keyword": "계획", "weight": 1, "notes": ""},
        {"enabled": True, "bucket": "frame_policy", "keyword": "추진", "weight": 1, "notes": ""},
        {"enabled": True, "bucket": "frame_policy", "keyword": "인허가", "weight": 1, "notes": ""},
        {"enabled": True, "bucket": "frame_positive", "keyword": "기대", "weight": 1, "notes": ""},
        {"enabled": True, "bucket": "frame_positive", "keyword": "환영", "weight": 1, "notes": ""},
        {"enabled": True, "bucket": "frame_positive", "keyword": "활성화", "weight": 1, "notes": ""},
        {"enabled": True, "bucket": "frame_critical", "keyword": "우려", "weight": 2, "notes": ""},
        {"enabled": True, "bucket": "frame_critical", "keyword": "비판", "weight": 2, "notes": ""},
        {"enabled": True, "bucket": "frame_critical", "keyword": "논란", "weight": 2, "notes": ""},
        {"enabled": True, "bucket": "frame_critical", "keyword": "반발", "weight": 2, "notes": ""},
        {"enabled": True, "bucket": "frame_critical", "keyword": "지연", "weight": 2, "notes": ""},
        {"enabled": True, "bucket": "frame_critical", "keyword": "실효성", "weight": 2, "notes": ""},
        {"enabled": True, "bucket": "frame_political", "keyword": "국회", "weight": 2, "notes": ""},
        {"enabled": True, "bucket": "frame_political", "keyword": "여당", "weight": 2, "notes": ""},
        {"enabled": True, "bucket": "frame_political", "keyword": "야당", "weight": 2, "notes": ""},
        {"enabled": True, "bucket": "frame_political", "keyword": "지자체", "weight": 2, "notes": ""},
        {"enabled": True, "bucket": "frame_political", "keyword": "부처", "weight": 2, "notes": ""},
        {"enabled": True, "bucket": "negative_signal", "keyword": "갈등", "weight": 1, "notes": ""},
        {"enabled": True, "bucket": "negative_signal", "keyword": "우려", "weight": 1, "notes": ""},
        {"enabled": True, "bucket": "negative_signal", "keyword": "비판", "weight": 1, "notes": ""},
        {"enabled": True, "bucket": "negative_signal", "keyword": "반발", "weight": 1, "notes": ""},
        {"enabled": True, "bucket": "opinion_signal", "keyword": "사설", "weight": 1, "notes": ""},
        {"enabled": True, "bucket": "opinion_signal", "keyword": "칼럼", "weight": 1, "notes": ""},
        {"enabled": True, "bucket": "opinion_signal", "keyword": "오피니언", "weight": 1, "notes": ""},
        {"enabled": True, "bucket": "opinion_signal", "keyword": "분석", "weight": 1, "notes": ""},
    ],
}

DEFAULT_RUNTIME_SETTINGS = [
    {
        "key": "analysis_reference_time",
        "value": "",
        "notes": "Blank = current execution time. Press-release sessions set their own start window automatically.",
    }
]


def clone_default_config():
    return deepcopy(DEFAULT_CONFIG)
